[context.deploy-preview]
    command = "hugo --buildFuture --buildDrafts --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/github"
  to = "https://github.com/navendu-pottekkat"

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/navendup/"

[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCWwMJ5SxVStO04W3nOrCiNA"

[[redirects]]
  from = "/resume"
  to = "https://drive.google.com/file/d/1jDFbGbvKDIWpFo9epExreqTyQCrGo1Vg/view?usp=sharing"

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/sudo_navendu"
